#!/usr/bin/env python3
"""Remove cached embeddings and vector database files.

Use this script to clean up temporary data generated by the RAG pipeline.
It deletes the ``data/cache``, ``data/embeddings`` and ``data/vectordb``
directories if they exist.  Be careful: this operation is irreversible.
"""

from __future__ import annotations

import shutil
from pathlib import Path


def main() -> None:
    base = Path(__file__).resolve().parents[1]  # generative_ai_project root
    targets = [
        base / "data" / "cache",
        base / "data" / "embeddings",
        base / "data" / "vectordb",
    ]
    for path in targets:
        if path.exists():
            shutil.rmtree(path)
            print(f"Removed {path}")
        else:
            print(f"{path} does not exist, skipping")


if __name__ == "__main__":
    main()
